[package]
name = "ltl"
version = "0.1.0"
authors = ["Alessio Coltellacci <lightplay8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.4", features = ["v4"] }
dot = "0.1"